name: mdns
version: 1.0.0
summary: mdns tools
description: mdns tools with UI

confinement: strict
base: core24
grade: stable

#slots:
#  dbus-avahi: # adjust accordingly to your app name
#    interface: dbus
#    bus: session
#    name: org.bar.super_cool_app # adjust accordingly to your app name and

#plugs:
#  avahi-svc:  # name that is used with 'snap connect' on plugs side
#    bus: system
#    interface: dbus
#    name: org.freedesktop.Avahi.Server2

apps:
  mdns:
    command: mdns
    extensions: [gnome]
    plugs:
      - network
      - network-bind
      - avahi-observe
      - avahi-control
#      - dbus
#      - avahi-svc
parts:
  mdns:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
architectures:
  - build-on: [ amd64 ]
  - build-on: [ arm64 ]