name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.5
      - run: flutter pub get
      - run: flutter build apk --release
      - name: Release APK
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./build/app/outputs/flutter-apk/app-release.apk
          body_path: ./.github/doc/DownloadDescription.md

  ios:
    name: iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.5
      - run: flutter config --no-enable-android
      - run: flutter pub get
      - run: flutter build ipa  --release --no-codesign
      - run: zip -r ios-release.zip ./build/ios/archive
      - name: Release iOS IPA
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ios-release.zip
          body_path: ./.github/doc/DownloadDescription.md

  linux:
    name: Linux
    runs-on: ubuntu-latest
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.24.5
      - name: Install required build tools for linux
        run: sudo apt-get update && sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev locate rpm patchelf libfuse2
      - name: Build linux release
        run: |
          flutter config --enable-linux-desktop
          flutter config --no-enable-android
          flutter pub get
          flutter build linux --release
      - run: zip -r linux-release.zip ./build/linux/x64/release/bundle
      - name: Release Linux Zip
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            linux-release.zip
          body_path: ./.github/doc/DownloadDescription.md
      - run: rm -rf ./build
      - name: Install snapcraft
        run: |
          sudo snap install snapcraft --classic
      - run: hash -r
      - name: Setup LXD
        uses: canonical/setup-lxd@v0.1.1
        with:
          channel: latest/stable
      - name: run snapcraft
        run: |
          snapcraft --use-lxd
      - run: snapcraft upload --release=stable *.snap

  #
  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.24.5
      - run: flutter config --enable-macos-desktop
      - run: flutter config --no-enable-android
      - run: flutter pub get
      - run: flutter build macos --debug
      - run: mkdir -p build/dmg
      - run: cp -R build/macos/Build/Products/Debug/mdns_ui.app build/dmg/mdns_ui.app
      - run: ln -s /Applications  build/dmg
      - run: ls build/dmg
      # https://github.com/create-dmg/create-dmg.git
      - run: hdiutil create -srcfolder build/dmg -volname "OpenIoTHub" -format UDZO -ov -imagekey zlib-level=9 mdns_ui.dmg
      - name: Release MacOS dmg
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./mdns_ui.dmg
          body_path: ./.github/doc/DownloadDescription.md
  #
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.24.5
      - run: flutter config --enable-windows-desktop
      - run: flutter config --no-enable-android
      - run: flutter pub get
      - run: flutter build windows --release
      - run: Compress-Archive -Path build\windows\x64\runner\Release -DestinationPath windows-release.zip
      - name: Release windows zip
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            windows-release.zip
          body_path: ./.github/doc/DownloadDescription.md

