name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  project-id: codes.merritt.FeelingFinder

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.24.5
#      - run: flutter pub upgrade
      - run: flutter pub get
      - run: flutter build apk --debug
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug-all.apk
          path: ./build/app/outputs/flutter-apk/app-debug.apk

  ios:
    name: iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.24.5
      - run: flutter config --no-enable-android
      - run: flutter pub get
      - run: flutter build ipa  --release --no-codesign
      - uses: actions/upload-artifact@v4
        with:
          name: Runner.xcarchive
          path: ./build/ios/archive/Runner.xcarchive

  linux:
    name: Linux
    runs-on: ubuntu-22.04
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.24.5
      - name: Install required build tools for linux
        run: sudo apt-get update && sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev locate rpm patchelf libfuse2
      - name: Build linux release
        run: |
          flutter config --enable-linux-desktop
          flutter config --no-enable-android
          flutter pub get
          flutter build linux --release
      - uses: actions/upload-artifact@v4
        with:
          name: linux-release.zip
          path: ./build/linux/x64/release/bundle
      - run: rm -rf ./build
      - name: Install snapcraft
        run: |
          sudo snap install snapcraft --classic
      - run: hash -r
      - name: Setup LXD
        uses: canonical/setup-lxd@v0.1.1
        with:
          channel: latest/stable
      - name: run snapcraft
        run: |
          snapcraft --use-lxd
      - run: ls -a
      - uses: actions/upload-artifact@v4
        with:
          name: mdns_1.0.0_amd64.snap
          path: ./mdns_1.0.0_amd64.snap
#
  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.24.5
      - run: flutter config --enable-macos-desktop
      - run: flutter config --no-enable-android
      - run: flutter pub get
      - run: flutter build macos --debug
      - run: mkdir -p build/dmg
      - run: cp -R build/macos/Build/Products/Debug/mdns_ui.app build/dmg/mdns_ui.app
      - run: ln -s /Applications  build/dmg
      - run: ls build/dmg
      # https://github.com/create-dmg/create-dmg.git
      - run: hdiutil create -srcfolder build/dmg -volname "OpenIoTHub" -format UDZO -ov -imagekey zlib-level=9 mdns_ui.dmg
      - uses: actions/upload-artifact@v4
        with:
          name: mdns_ui.dmg
          path: ./mdns_ui.dmg
